name: text-py
version: 0.1.0
homepage: https://github.com/morloclib/text-py
synopsis: Python implementations for text operations
description: Python implementations for text operations
category: data
license: MIT
author: "Zebulun Arendsee"
maintainer: "z@morloc.io"
github: https://github.com/morloclib/text-py
bug-reports: https://github.com/morloclib/text-py
